# Generated by Codex on 2026-02-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0002_draft_deleted_at"),
        ("drafts", "0002_draftsandbox"),
    ]

    operations = []
