# Generated by Django 4.2.11 on 2026-02-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_id', models.IntegerField()),
                ('version_a', models.IntegerField()),
                ('version_b', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
