# Generated by Django 4.2.11 on 2026-02-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("lawyer", "Lawyer"),
                    ("law_student", "Law Student"),
                ],
                default="lawyer",
                max_length=20,
            ),
        ),
    ]
