# Generated by Django 4.2.11 on 2026-02-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Precedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('NDA', 'Non Disclosure Agreement'), ('EMPLOYMENT', 'Employment Contract'), ('SERVICE', 'Service Agreement'), ('NOTICE', 'Legal Notice')], max_length=50)),
                ('content', models.TextField()),
                ('is_clause_template', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
