# Generated by Django 4.2.11 on 2026-02-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('clause_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('TERMINATION', 'Termination'), ('CONFIDENTIALITY', 'Confidentiality'), ('LIABILITY', 'Liability'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
