# Generated by Django 4.2.11 on 2026-02-26 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drafts', '0001_initial'),
        ('clauses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='drafts.draft'),
        ),
    ]
