# Generated by Django 4.2.11 on 2026-02-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0002_compliance_jurisdiction_refactor"),
        ("drafts", "0002_draftsandbox"),
        ("users", "0002_update_roles"),
        ("clauses", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClauseLibraryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                (
                    "clause_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "Payment"),
                            ("TERMINATION", "Termination"),
                            ("CONFIDENTIALITY", "Confidentiality"),
                            ("LIABILITY", "Liability"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("fallback_alternatives", models.JSONField(blank=True, default=list)),
                ("negotiation_playbook", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clause_library_entries",
                        to="compliance.documenttype",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ClauseRedlineSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_text", models.TextField()),
                ("suggested_text", models.TextField()),
                ("rationale", models.TextField(blank=True)),
                ("diff_preview", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clause",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redline_suggestions",
                        to="clauses.clause",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redline_suggestions",
                        to="drafts.draft",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_redlines",
                        to="users.user",
                    ),
                ),
                (
                    "suggested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_redlines",
                        to="users.user",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
