# Generated by Django 4.2.11 on 2026-02-26 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancerule",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="compliance.documenttype",
            ),
        ),
        migrations.AddField(
            model_name="compliancerule",
            name="jurisdiction",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="compliancerule",
            name="rule_code",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentactmapping",
            name="jurisdiction",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="legalact",
            name="jurisdiction",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mandatoryclause",
            name="jurisdiction",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mandatoryclause",
            name="required_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prohibitedword",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="compliance.documenttype",
            ),
        ),
        migrations.AddField(
            model_name="prohibitedword",
            name="jurisdiction",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="requiredterm",
            name="jurisdiction",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="riskpattern",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="compliance.documenttype",
            ),
        ),
        migrations.AddField(
            model_name="riskpattern",
            name="jurisdiction",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="structurerule",
            name="jurisdiction",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="compliancerule",
            constraint=models.UniqueConstraint(
                fields=("document_type", "jurisdiction", "rule_code"),
                name="unique_compliance_rule_per_jurisdiction",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentactmapping",
            constraint=models.UniqueConstraint(
                fields=("document_type", "legal_act", "jurisdiction"),
                name="unique_document_act_mapping_per_jurisdiction",
            ),
        ),
        migrations.AddConstraint(
            model_name="mandatoryclause",
            constraint=models.UniqueConstraint(
                fields=("document_type", "jurisdiction", "clause_type"),
                name="unique_mandatory_clause_per_jurisdiction",
            ),
        ),
        migrations.AddConstraint(
            model_name="requiredterm",
            constraint=models.UniqueConstraint(
                fields=("document_type", "jurisdiction", "term"),
                name="unique_required_term_per_jurisdiction",
            ),
        ),
        migrations.AddConstraint(
            model_name="structurerule",
            constraint=models.UniqueConstraint(
                fields=("document_type", "jurisdiction"),
                name="unique_structure_rule_per_jurisdiction",
            ),
        ),
    ]
